version = 0.1
[default.deploy.parameters]
stack_name = "vehiculos-api-lebc-9c"
resolve_s3 = true
s3_prefix = "vehiculos-api-lebc-9c"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
